// STACKS
export const MAIN_STACK = 'MAIN_STACK'

// SCREENS
export const MAIN_SCREEN = 'MAIN_SCREEN'
export const CREATE_TASK_SCREEN = 'CREATE_TASK_SCREEN'
export const EDIT_TASK_SCREEN = 'EDIT_TASK_SCREEN'